apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neenakost
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: neenakost
    newName: rg.fr-par.scw.cloud/djnd/neenakost
    newTag: '74f63b2281490921b22f23c7c1dbe1bee74f1f03'
